// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy8uT-1Ce1tntOEvcWmWwl4l-rYvBujNc',
    appId: '1:177260480258:web:06c1940115131122f9241b',
    messagingSenderId: '177260480258',
    projectId: 'fitness-app-934f0',
    authDomain: 'fitness-app-934f0.firebaseapp.com',
    storageBucket: 'fitness-app-934f0.firebasestorage.app',
    measurementId: 'G-75MB5VWEBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDniYN0PNpl3V4DSp7b9QxEw3Ja8uhcQjk',
    appId: '1:177260480258:android:afc9f3b7d1b1617bf9241b',
    messagingSenderId: '177260480258',
    projectId: 'fitness-app-934f0',
    storageBucket: 'fitness-app-934f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Lembgud7peNehDfFX_Rrbc7_1i5WZQc',
    appId: '1:177260480258:ios:e62208683def042bf9241b',
    messagingSenderId: '177260480258',
    projectId: 'fitness-app-934f0',
    storageBucket: 'fitness-app-934f0.firebasestorage.app',
    iosClientId: '177260480258-2leljvmc4u311ee936sc0mfdihlod7ij.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Lembgud7peNehDfFX_Rrbc7_1i5WZQc',
    appId: '1:177260480258:ios:e62208683def042bf9241b',
    messagingSenderId: '177260480258',
    projectId: 'fitness-app-934f0',
    storageBucket: 'fitness-app-934f0.firebasestorage.app',
    iosClientId: '177260480258-2leljvmc4u311ee936sc0mfdihlod7ij.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy8uT-1Ce1tntOEvcWmWwl4l-rYvBujNc',
    appId: '1:177260480258:web:06c1940115131122f9241b',
    messagingSenderId: '177260480258',
    projectId: 'fitness-app-934f0',
    authDomain: 'fitness-app-934f0.firebaseapp.com',
    storageBucket: 'fitness-app-934f0.firebasestorage.app',
    measurementId: 'G-75MB5VWEBW',
  );

}